# Generated by Django 2.0.5 on 2018-06-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
